title: Snippets
description: Just aim you can hit it!
author: Vijai 
baseurl: /blog
timezone: Europe/Paris
# social links
#twitter_username: vijaidjearam # DO NOT include the @ character, or else the build will fail!
github_username:  vijaidjearam # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
show_tags: true # set to false to remove tags on the homepage
plugins:
  - jemoji
