title: Snippets
description: I’m not a JavaScript fan, but needs must.
author: Vijai 
baseurl: /Blog
timezone: Europe/Paris
# social links
#twitter_username: thesubmarine # DO NOT include the @ character, or else the build will fail!
github_username:  vijai Djearam # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
show_tags: false # set to false to remove tags on the homepage
